import { homedir } from "node:os"
import { join } from "node:path"
import { parsePorts } from "@server/view/configuration"

/**
 * The installer's decisions, separated from its conversation: everything
 * here is pure or near-pure (the only effectful reads are this machine's
 * home directory), so the suite can hold the installed shape stable without
 * running prompts, extracting archives, or touching real services.
 *
 * The layout the installer produces is the RUNBOOK's production layout:
 * one destination directory holding the distribution's files plus a
 * generated start wrapper and environment file, state under SERAPHOS_HOME,
 * and - when the operator asks - a service registered at the user level.
 * Nothing the installer writes needs an administrator.
 */

/** What one installation run configures. */
export interface InstallerAnswers {

    /** The System's state root (SERAPHOS_HOME). */
    home: string

    /** The interface the System binds (SERAPHOS_HOST). */
    host: string

    /** The port selection as written to the environment (SERAPHOS_PORT). */
    ports: string

    /** The assistant's endpoint, or null to leave the assistant off. */
    llmBaseUrl: string | null

    /** The endpoint's key, or null. Never echoed back by the installer. */
    llmApiKey: string | null

    /** The model served at that endpoint (SERAPH_LLM_MODEL). */
    llmModel: string

    /** The embeddings model for the user's file search (SERAPH_LLM_EMBED_MODEL). */
    llmEmbedModel: string
}

/** The installer's answers before it asks anything. */
export function defaultAnswers(): InstallerAnswers {

    return {
        home: homeDefault(),
        host: "localhost",
        ports: "6400-6499",
        llmBaseUrl: null,
        llmApiKey: null,
        llmModel: "llama3.2",
        llmEmbedModel: "nomic-embed-text"
    }
}

/** The default state root: the RUNBOOK's `~/.seraphos`. */
export function homeDefault() {

    return resolveHome(".seraphos")
}

/** The default installation destination: inside the state root, apart from its state. */
export function destinationDefault() {

    return resolveHome(".seraphos", "system")
}

function resolveHome(...of: string[]) {

    return join(homedir(), ...of)
}

/** Whether a destination may take the installation as it stands. */
export type DestinationVerdict = "fresh" | "empty" | "occupied"

/** Judges a destination from what the caller already saw on the disk. */
export function destinationVerdict(exists: boolean, entryCount: number): DestinationVerdict {

    if (!exists) return "fresh"

    return entryCount === 0 ? "empty" : "occupied"
}

/** The port selection answer, validated by the System's own parser. */
export function validPorts(value: string): string | null {

    const selection = value.trim()

    if (!selection) return null

    try { parsePorts(selection, "SERAPHOS_PORT") }

    catch { return null }

    return selection
}

/** The assistant endpoint answer: blank or whitespace means off. */
export function assistantEndpoint(value: string): string | null {

    const endpoint = value.trim()

    return endpoint ? endpoint.replace(/\/+$/, "") : null
}

/**
 * The environment file's text. The wrapper reads it before starting the
 * server; values already in the caller's environment win over the file, so
 * a service drop-in can override without editing the file.
 */
export function renderEnvironment(answers: InstallerAnswers): string {

    const lines: string[] = [
        "# Seraph OS server environment, generated by scripts/install.ts.",
        "# Values already set in the service's own environment win over this file."
    ]

    for (const [key, value] of [
        ["SERAPHOS_HOME", answers.home],
        ["SERAPHOS_HOST", answers.host],
        ["SERAPHOS_PORT", answers.ports]
    ] as const) lines.push(`${key}=${value}`)

    if (answers.llmBaseUrl) {

        lines.push("")

        lines.push("# The assistant's OpenAI-compatible endpoint.")

        lines.push(`SERAPH_LLM_BASE_URL=${answers.llmBaseUrl}`)

        lines.push(`SERAPH_LLM_MODEL=${answers.llmModel}`)

        lines.push(`SERAPH_LLM_EMBED_MODEL=${answers.llmEmbedModel}`)

        if (answers.llmApiKey) lines.push(`SERAPH_LLM_API_KEY=${answers.llmApiKey}`)
    }

    return lines.join("\n") + "\n"
}

/** The start wrapper's source: reads the environment file, then starts the server. */
export function startWrapperSource(): string {

    return [
        "// Seraph OS start wrapper, generated by scripts/install.ts.",
        "// Loads seraphos.env into the process environment (values already set",
        "// win), then runs the server in this directory, forwarding its exit.",
        "",
        "import { spawn } from \"node:child_process\"",
        "import { readFileSync } from \"node:fs\"",
        "import { dirname, join } from \"node:path\"",
        "import { fileURLToPath } from \"node:url\"",
        "",
        "const here = dirname(fileURLToPath(import.meta.url))",
        "",
        "for (const line of readFileSync(join(here, \"seraphos.env\"), \"utf8\").split(/\\r?\\n/)) {",
        "",
        "    const match = /^([A-Z0-9_]+)=(.*)$/.exec(line)",
        "",
        "    if (match && process.env[match[1]] === undefined) process.env[match[1]] = match[2]",
        "}",
        "",
        "spawn(process.execPath, [\"server/main.js\"], { cwd: here, stdio: \"inherit\" })",
        "    .on(\"exit\", code => { process.exitCode = code ?? 1 })",
        ""
    ].join("\n")
}

/** One service registration the installer offers to write and run. */
export interface ServicePlan {

    /** Files to write, as destination-content pairs (relative to ~). */
    readonly files: ReadonlyArray<{ readonly path: string, readonly content: string, readonly mode: number }>

    /** Commands that activate what was written, in order, at the user level. */
    readonly commands: readonly string[]

    /** What to tell the operator when the plan is not automatic. */
    readonly notes: readonly string[]
}

/**
 * The per-user service plan for one platform: systemd (Linux, user unit),
 * launchd (macOS, LaunchAgent), a logon scheduled task (Windows), and
 * printed instructions elsewhere. User-level everywhere: the System runs
 * as its operator, and no step here asks for an administrator.
 */
export function servicePlan(
    platform: NodeJS.Platform,
    installation: { readonly node: string, readonly wrapper: string, readonly destination: string }
): ServicePlan {

    if (platform === "linux") {

        const unit = [
            "[Unit]",
            "Description=Seraph OS System",
            "",
            "[Service]",
            `ExecStart=${installation.node} ${installation.wrapper}`,
            `WorkingDirectory=${installation.destination}`,
            "Restart=on-failure",
            "",
            "[Install]",
            "WantedBy=default.target",
            ""
        ].join("\n")

        return {
            files: [{ path: ".config/systemd/user/seraphos.service", content: unit, mode: 0o600 }],
            commands: [
                "systemctl --user daemon-reload",
                "systemctl --user enable --now seraphos.service"
            ],
            notes: []
        }
    }

    if (platform === "darwin") {

        const plist = [
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
            "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">",
            "<plist version=\"1.0\">",
            "<dict>",
            "    <key>Label</key>",
            "    <string>app.seraphos.system</string>",
            "    <key>ProgramArguments</key>",
            "    <array>",
            `        <string>${installation.node}</string>`,
            `        <string>${installation.wrapper}</string>`,
            "    </array>",
            "    <key>RunAtLoad</key>",
            "    <true/>",
            "    <key>KeepAlive</key>",
            "    <true/>",
            "</dict>",
            "</plist>",
            ""
        ].join("\n")

        return {
            files: [{ path: "Library/LaunchAgents/app.seraphos.system.plist", content: plist, mode: 0o600 }],
            commands: ["launchctl load Library/LaunchAgents/app.seraphos.system.plist"],
            notes: []
        }
    }

    if (platform === "win32") {

        // /tr takes ONE quoted argument whose inner quotes are doubled
        // (cmd's own rule), so the task runs both halves together:
        // schtasks /tr "\"node.exe\" \"wrapper.mjs\"".
        const target = `\\"${installation.node}\\" \\"${installation.wrapper}\\"`

        return {
            files: [],
            commands: [["schtasks", "/create", "/f", "/tn", "SeraphOS", "/sc", "onlogon", "/tr", target].map(shellWord).join(" ")],
            notes: ["The task starts on your next sign-in; start it now with: schtasks /run /tn SeraphOS"]
        }
    }

    return {
        files: [],
        commands: [],
        notes: [
            `No automatic service for ${platform}: run the System with`,
            `  ${installation.node} ${installation.wrapper}`,
            "from your service manager of choice."
        ]
    }
}

/** Quotes one word for a Windows command line the way cmd.exe reads it. */
function shellWord(word: string) {

    return /^[A-Za-z0-9_/.:\\-]+$/.test(word) ? word : `"${word}"`
}

/**
 * How this machine installs the distribution's production dependencies.
 * Windows resolves npm through its own CLI script; elsewhere `npm` is on
 * the path. The flags match the distribution contract's own install.
 */
export function npmInstallCommand(platform: NodeJS.Platform, node: string): { command: string, prefix: readonly string[], args: string[] } {

    const args = ["install", "--omit=dev", "--no-audit", "--no-fund", "--no-package-lock"]

    if (platform === "win32") return { command: node, prefix: [join(dirnameOf(node), "node_modules", "npm", "bin", "npm-cli.js")], args }

    return { command: "npm", prefix: [], args }
}

function dirnameOf(path: string) {

    return path.slice(0, Math.max(path.lastIndexOf("/"), path.lastIndexOf("\\"), 0))
}

/**
 * The freshest release archive among a directory listing: `seraphos@`
 * prefixed, parsed by semver, highest version wins. Checksums, signatures,
 * and anything else are not archives.
 */
export function chooseArchive(entries: readonly string[]): string | null {

    const archives = entries
        .map(entry => /^(seraphos@(\d+)\.(\d+)\.(\d+)\.zip)$/.exec(entry))
        .filter((match): match is RegExpExecArray => match !== null)
        .sort((one, two) => semver(two) - semver(one))

    return archives.length ? archives[0][1] : null

    function semver(match: RegExpExecArray) {

        return Number(match[2]) * 1_000_000 + Number(match[3]) * 1_000 + Number(match[4])
    }
}
